export const monitorPage = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Research Run Monitor</title>
<style>
:root{color-scheme:dark;--bg:#0f141a;--panel:#171e27;--line:#2b3744;--text:#e8edf2;--muted:#94a3b3;--green:#45d483;--amber:#f2bd62;--red:#f27676;--blue:#71b7ff}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 -apple-system,BlinkMacSystemFont,"SF Pro Text",sans-serif}main{max-width:1440px;margin:auto;padding:24px}header{display:flex;gap:12px;align-items:end;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:18px}h1{font-size:22px;margin:0}h2{font-size:15px;margin:0 0 12px;color:var(--muted)}input,button{font:inherit;border:1px solid var(--line);background:#10161d;color:var(--text);padding:9px 11px;border-radius:5px}input{min-width:360px}button{cursor:pointer;background:#26384b}button:hover{border-color:var(--blue)}.grid{display:grid;grid-template-columns:1fr 1.5fr;gap:14px;margin-top:16px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:6px;padding:16px;min-width:0}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.stat{border-left:3px solid var(--blue);padding:9px 10px;background:#121920}.stat b{display:block;font-size:21px}.stat span{color:var(--muted);font-size:12px}.status{font-weight:700}.completed{color:var(--green)}.running{color:var(--blue)}.failed{color:var(--red)}.cancelled,.queued{color:var(--amber)}.events{height:520px;overflow:auto;display:flex;flex-direction:column;gap:7px}.event{border-left:2px solid var(--line);padding:7px 9px;background:#121920}.event time{color:var(--muted);font-size:11px;margin-right:8px}.event.search{border-left-color:var(--blue)}.event.fetch{border-left-color:var(--green)}.event.error{border-left-color:var(--red)}pre{white-space:pre-wrap;overflow-wrap:anywhere;margin:8px 0 0;color:#c5d0db;font:12px/1.45 ui-monospace,SFMono-Regular,monospace}.answer{max-height:420px;overflow:auto;color:#d8e6f2}.links a{color:var(--blue);display:block;overflow-wrap:anywhere}.empty{color:var(--muted);padding:25px 0;text-align:center}@media(max-width:800px){main{padding:14px}header{display:block}input{min-width:0;width:100%;margin:12px 0}.grid{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}}
</style></head><body><main><header><div><h1>Research Run Monitor</h1><div id="question" style="color:var(--muted);margin-top:4px">等待 runId</div></div><form id="form"><label for="run">Run ID</label><input id="run" required placeholder="run_..."><button>连接</button></form></header><section class="panel" style="margin-top:16px"><h2>当前状态</h2><div id="status" class="status">未连接</div><div class="stats"><div class="stat"><b id="searches">0</b><span>搜索结果</span></div><div class="stat"><b id="fetches">0</b><span>抓取页面</span></div><div class="stat"><b id="events">0</b><span>事件数</span></div><div class="stat"><b id="errors">0</b><span>协议错误</span></div></div></section><div class="grid"><section class="panel"><h2>最终答案</h2><div id="answer" class="answer empty">尚未生成</div><h2 style="margin-top:20px">报告</h2><div id="links" class="links empty">尚未生成</div></section><section class="panel"><h2>实时事件</h2><div id="eventList" class="events"><div class="empty">输入 Run ID 后开始监听</div></div></section></div></main>
<script>
const POLL_INTERVAL_MS=1500;const LIST_INTERVAL_MS=2000;const MAX_RENDERED_EVENTS=500;const AUTH_STORAGE_KEY='researchHttpAuthToken';
const $=id=>document.getElementById(id);let runId=new URLSearchParams(location.search).get('runId')||'';let timer;let listTimer;let generation=0;let afterSequence=0;let retainedEvents=[];
function loadAuthToken(){const fragment=new URLSearchParams(location.hash.slice(1));const hasFragmentToken=fragment.has('token');const fragmentToken=fragment.get('token')||'';let token=fragmentToken;try{if(hasFragmentToken){if(fragmentToken)sessionStorage.setItem(AUTH_STORAGE_KEY,fragmentToken);else sessionStorage.removeItem(AUTH_STORAGE_KEY)}token=sessionStorage.getItem(AUTH_STORAGE_KEY)||fragmentToken}catch{}if(hasFragmentToken)history.replaceState(null,'',location.pathname+location.search);return token}
const authToken=loadAuthToken();
function apiFetch(url){return authToken?fetch(url,{headers:{Authorization:'Bearer '+authToken}}):fetch(url)}
function text(v){return typeof v==='string'?v:JSON.stringify(v??null,null,2)}
function element(tag,className,value){const node=document.createElement(tag);if(className)node.className=className;if(value!==undefined)node.textContent=String(value);return node}
function empty(node,message){node.replaceChildren(element('div','empty',message))}
function statusClass(status){return ['completed','running','failed','cancelled','queued'].includes(status)?status:''}
function renderRun(run){$('question').textContent=run.task?.question||'';const s=typeof run.status==='string'?run.status:'unknown';const reason=run.result?.state?.interrupted?.reason;$('status').textContent=s+(reason?' · '+reason:'');$('status').className='status '+statusClass(s);$('searches').textContent=run.result?.state?.searchResults?.length??0;$('fetches').textContent=run.result?.state?.fetchedPages?.length??0;const runEvents=Array.isArray(run.events)?run.events:[];$('events').textContent=runEvents.length;$('errors').textContent=runEvents.filter(e=>e.type==='agent.protocol_error').length;const answer=run.result?.state?.finalAnswer;$('answer').textContent=answer==null?'尚未生成':text(answer);$('answer').className=answer==null?'answer empty':'answer';renderReport(run.report)}
function renderReport(report){const links=$('links');links.replaceChildren();links.className='links';if(!report){links.textContent='尚未生成';links.className='links empty';return}for(const key of ['jsonPath','markdownPath','htmlPath']){const value=report[key];if(typeof value!=='string')continue;let reportPath=value;while(reportPath.startsWith('/'))reportPath=reportPath.slice(1);const link=element('a','',key+': '+value);link.href='/'+reportPath;link.target='_blank';link.rel='noopener noreferrer';links.append(link)}if(!links.childElementCount){links.textContent='尚未生成';links.className='links empty'}}
function eventKey(event){const sequence=Number(event?.sequence);return Number.isFinite(sequence)?'sequence:'+sequence:'legacy:'+String(event?.timestamp||'')+'\u0000'+String(event?.type||'')+'\u0000'+text(event?.payload)}
function mergeEvents(incoming){const merged=new Map();for(const event of retainedEvents.concat(Array.isArray(incoming)?incoming:[]))merged.set(eventKey(event),event);retainedEvents=[...merged.values()].sort((left,right)=>{const a=Number(left?.sequence);const b=Number(right?.sequence);if(Number.isFinite(a)&&Number.isFinite(b))return a-b;if(Number.isFinite(a))return -1;if(Number.isFinite(b))return 1;return 0}).slice(-MAX_RENDERED_EVENTS);for(const event of Array.isArray(incoming)?incoming:[]){const sequence=Number(event?.sequence);if(Number.isFinite(sequence))afterSequence=Math.max(afterSequence,sequence)}}
function renderEvents(events){const box=$('eventList');if(!events.length){empty(box,'暂无事件');return}const fragment=document.createDocumentFragment();for(const event of events){const type=typeof event?.type==='string'?event.type:'unknown';const kind=type.includes('error')?'error':type.startsWith('search')?'search':type.startsWith('fetch')?'fetch':'';const item=element('div','event '+kind);const time=element('time','',new Date(event?.timestamp).toLocaleTimeString());const label=element('b','',type);const payload=element('pre','',text(event?.payload));item.append(time,label,payload);fragment.append(item)}box.replaceChildren(fragment);box.scrollTop=box.scrollHeight}
function showList(runs){const box=$('eventList');if(!runs.length){empty(box,'当前没有 run');return}const fragment=document.createDocumentFragment();for(const run of runs){const id=typeof run?.runId==='string'?run.runId:'';const status=typeof run?.status==='string'?run.status:'unknown';const button=element('button','event');button.type='button';button.style.textAlign='left';button.style.width='100%';button.dataset.run=id;const state=element('b',statusClass(status),status);const runLabel=element('span','',id);const question=element('span','',run?.task?.question||'');question.style.color='var(--muted)';const created=element('time','',new Date(run?.createdAt).toLocaleString());button.append(state,document.createTextNode(' '),runLabel,document.createElement('br'),question,document.createElement('br'),created);button.addEventListener('click',()=>connect(id));fragment.append(button)}box.replaceChildren(fragment)}
function clearTimers(){clearTimeout(timer);clearTimeout(listTimer);timer=undefined;listTimer=undefined}
async function loadList(expectedGeneration){try{const response=await apiFetch('/v1/research');if(!response.ok)throw Error('list_failed');const body=await response.json();if(expectedGeneration!==generation||runId)return;showList(Array.isArray(body.runs)?body.runs:[])}catch(error){if(expectedGeneration!==generation||runId)return;empty($('eventList'),'列表加载失败: '+(error instanceof Error?error.message:String(error)))}finally{if(expectedGeneration===generation&&!runId)listTimer=setTimeout(()=>loadList(expectedGeneration),LIST_INTERVAL_MS)}}
function connect(nextRunId){generation+=1;clearTimers();runId=typeof nextRunId==='string'?nextRunId:'';afterSequence=0;retainedEvents=[];if(!runId){history.replaceState(null,'','/monitor');$('run').value='';void loadList(generation);return}history.replaceState(null,'','/monitor?runId='+encodeURIComponent(runId));$('run').value=runId;void poll(generation)}
async function poll(expectedGeneration){if(!runId||expectedGeneration!==generation)return;let continuePolling=true;try{const base='/v1/research/'+encodeURIComponent(runId);const [runResponse,eventResponse]=await Promise.all([apiFetch(base),apiFetch(base+'/events?afterSequence='+encodeURIComponent(afterSequence))]);if(!runResponse.ok)throw Error('run_not_found');if(!eventResponse.ok)throw Error('events_unavailable');const [run,eventBatch]=await Promise.all([runResponse.json(),eventResponse.json()]);if(expectedGeneration!==generation)return;renderRun(run);mergeEvents(eventBatch.events||[]);renderEvents(retainedEvents);const terminal=['completed','interrupted','failed','cancelled'].includes(run.status);continuePolling=!(terminal&&run.reportStatus!=='pending')}catch(error){if(expectedGeneration!==generation)return;$('status').textContent='连接失败: '+(error instanceof Error?error.message:String(error));$('status').className='status failed'}finally{if(expectedGeneration===generation&&runId&&continuePolling)timer=setTimeout(()=>poll(expectedGeneration),POLL_INTERVAL_MS)}}
$('form').onsubmit=event=>{event.preventDefault();connect($('run').value.trim())};$('run').value=runId;if(runId)void poll(generation);else void loadList(generation)
</script></body></html>`;
